version: '3.8'

services:
  backend:
    build: ./node-backend
    ports:
      - "5000:5000"
    environment:
      - ACCESSTOKEN=${ACCESSTOKEN}
    networks:
      - app-network

  frontend:
    build:
      context: ./react-frontend
      args:
        ACCESSTOKEN: ${ACCESSTOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
